# Generated by Django 4.0.6 on 2022-07-11 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendAPI', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balance',
            name='account_no',
        ),
        migrations.AddField(
            model_name='balance',
            name='account_no',
            field=models.ManyToManyField(max_length=15, to='backendAPI.accounts'),
        ),
    ]
