# Generated by Django 4.0.6 on 2022-07-11 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendAPI', '0005_alter_accounts_account_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='account_no',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
