# Generated by Django 4.0.6 on 2022-07-13 12:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('backendAPI', '0009_rename_soft_delete_user_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='id',
            field=models.BigIntegerField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='balance',
            name='id',
            field=models.BigIntegerField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigIntegerField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
