# Generated by Django 4.0.6 on 2022-07-13 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backendAPI', '0013_alter_accounts_id_alter_balance_id_alter_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='full_name',
            new_name='name',
        ),
    ]
